
name: Build and deploy Jekyll to a remote hosting via rsync

on:
  push:
    branches:
      - master

jobs:
  jekyll:
    name: Build and deploy Jekyll site
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      uses: jerryjvl/jekyll-build-action@v1
    
    - name: Show files
      run: ls * ; ls _site/*

    - name: Deploy to hosting via rsync
      uses: burnett01/rsync-deployments@4.1
      with:
        switches: -avzr --delete
        path: /_site/*
        remote_path: site/
        remote_host: ${{ secrets.DEPLOY_HOST }}
        remote_port: ${{ secrets.DEPLOY_PORT }}
        remote_user: ${{ secrets.DEPLOY_USER }}
        remote_key: ${{ secrets.DEPLOY_KEY }}
      